
GET https://localhost/api/definitions
Content-Type: application/ld+json

###

GET https://localhost/api/definitions?page=1&itemsPerPage=30
Content-Type: application/ld+json

###

GET https://localhost/api/definitions?definition_type=feature
Content-Type: application/ld+json

###

GET https://localhost/api/definitions/{{definitionId}}
Content-Type: application/ld+json