
GET https://localhost/api/landlords
Content-Type: application/ld+json

###

GET https://localhost/api/landlords?page=1&itemsPerPage=30
Content-Type: application/ld+json

###

GET https://localhost/api/landlords/{{landlordId}}
Content-Type: application/ld+json

###

###################################### NO FUNCIONA ######################################
POST https://localhost/api/landlords
Content-Type: application/ld+json
###################################### /NO FUNCIONA ######################################