
GET https://localhost/api/neighborhoods
Content-Type: application/ld+json

###

GET https://localhost/api/neighborhoods?page=1&itemsPerPage=30
Content-Type: application/ld+json

###

GET https://localhost/api/neighborhoods/{{neighborhoodId}}
Content-Type: application/ld+json