
GET https://localhost/api/users
Content-Type: application/ld+json

###

GET https://localhost/api/users/{{userId}}
Content-Type: application/ld+json

###

POST https://localhost/api/users/login
Content-Type: application/json

{
  "username": "emailprueba@gmail.com",
  "password": "Password1!"
}


###################################### NO IMPLEMENTADO ######################################
GET https://localhost/api/users/me
Content-Type: application/ld+json
###################################### /NO IMPLEMENTADO ######################################

###

POST https://localhost/api/users
Content-Type: application/json

{
  "email": "email@gmail.com",
  "firstName": "Nombre",
  "lastName": "Apellidos",
  "password": "Password0!"
}