providers:
    file:
        directory: "/etc/traefik/config/"
    docker: {}

entryPoints:
    http:
        address: ":80"
    https:
        address: ":443"
    traefik:
        address: ":8080"
    supervisor:
        address: ":9001"
    rabbit-management:
        address: ":15672"

certificatesResolvers:
    letsencrypt:
        acme:
            email: "samuel.gracia@nodrizatech.com"
            storage: "/etc/traefik/acme.json"
            httpChallenge:
                entrypoint: http
            # testing server:
            # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

api:
    dashboard: true

log:
    level: info
    format: json